services:
  frontend:
    image: chunkanglu:quirknotes_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: chunkanglu:quirknotes_backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"